RISCV_PREFIX        = riscv32-unknown-elf-
ROOTDIR             = $(shell cd .. && pwd)
FREERTOS_SOURCE_DIR = $(ROOTDIR)/Source

CC                  = $(RISCV_PREFIX)gcc
OBJDUMP             = $(RISCV_PREFIX)objdump
OBJCOPY             = $(RISCV_PREFIX)objcopy
READELF             = $(RISCV_PREFIX)readelf

RISCV_GCC_OPTS      = -march=rv32im -nostdlib -nostartfiles

